Refactored to work in the 'stage' folder and copy the result when complete

diff --git a/wrapper-4-genFilter b/wrapper-4-genFilter
--- a/wrapper-4-genFilter
+++ b/wrapper-4-genFilter
@@ -1,15 +1,21 @@
 #!/bin/bash
+set -u
+trap "echo Script terminated with non-zero: $?" ERR
+
+export EMAIL_4_TCOFFEE="tcoffee.msa@gmail.com"
+export TMP_4_TCOFFEE="$TMPDIR/.tcoffee/tmp/"
+export CACHE_4_TCOFFEE="$TMPDIR/.tcoffee/cache/"
+export LOCKDIR_4_TCOFFEE="$TMPDIR/.tcoffee/lck"
+mkdir -p $TMP_4_TCOFFEE
+mkdir -p $CACHE_4_TCOFFEE
+mkdir -p $LOCKDIR_4_TCOFFEE
+
 
 reformat_cmd="t_coffee -other_pg seq_reformat"
 gblock_cmd="Gblocks"
 trimal_cmd="trimal"
 tcoffee_cmd="t_coffee"
 weiSeqboot_cmd="wei_seqboot -n 1 -r 0"
-
-fa_f="MSA.fa"
-phylip_f="MSA.phylip"
-tmp_f="tmp.fa"
-sa_f="prob_pair.sa"
 
 tip_p=$1
 var_p=$2
@@ -18,68 +24,69 @@ aln=$4
 filter=$5
 set_p=$(printf "%03d" $SGE_TASK_ID)
 
-input_fa="$(pwd)/$tip_p/$var_p/len$len/set$set_p/OA/$aln/MSA.fa"
-input_phylip="$(pwd)/$tip_p/$var_p/len$len/set$set_p/OA/$aln/MSA.phylip"
-out_p="$tip_p/$var_p/len$len/set$set_p/$filter/$aln/"
+input_fa="${DATA_FOLDER}/$tip_p/$var_p/len$len/set$set_p/OA/$aln/MSA.fa"
+input_phylip="${DATA_FOLDER}/$tip_p/$var_p/len$len/set$set_p/OA/$aln/MSA.phylip"
+out_p="${DATA_FOLDER}/$tip_p/$var_p/len$len/set$set_p/$filter/$aln/"
+
+#
+# The file to be returned 
+#
+phylip_f="MSA.phylip"
+
+#
+# the files below appears to be used as temporary file,
+# so use relative path 
+#
+tmp_f="tmp.fa"
+sa_f="prob_pair.sa"
+
+#
+# Move to the scratch DIR
+# 
+cd $TMPDIR
+
 
 if [ -e $input_fa ]
 then   
   echo "process $input_fa"
   
-  [ ! -e $out_p ] && mkdir -p $out_p
-  cd $out_p
-  
   cp $input_fa $tmp_f
   case $filter in
   "TG")
-    if [ ! -e $phylip_f ]
-    then
-     $trimal_cmd -in $tmp_f -out tmp.trim -gappyout
-     $reformat_cmd -in tmp.trim -output phylip > $phylip_f
-    else
-     echo "SKIP: $phylip_f exists"
-    fi
+    $trimal_cmd -in $tmp_f -out tmp.trim -gappyout
+    $reformat_cmd -in tmp.trim -output phylip > $phylip_f
     ;;
   "TS")
-    if [ ! -e $phylip_f ]
-    then
-     $trimal_cmd -in $tmp_f -out tmp.trim -strictplus
-     $reformat_cmd -in tmp.trim -output phylip > $phylip_f
-    else
-     echo "SKIP: $phylip_f exists"
-    fi
+    $trimal_cmd -in $tmp_f -out tmp.trim -strictplus
+    $reformat_cmd -in tmp.trim -output phylip > $phylip_f
     ;;    
   "GS")
-    if [ ! -e $phylip_f ]
-    then
-     $gblock_cmd $tmp_f -t=p
-     $reformat_cmd -in $tmp_f-gb -output phylip > $phylip_f
-    else
-     echo "SKIP: $phylip_f exists"
-    fi
+    $gblock_cmd $tmp_f -t=p
+    $reformat_cmd -in $tmp_f-gb -output phylip > $phylip_f
     ;;
   "GR")
-    if [ ! -e $phylip_f ]
-    then
-     $gblock_cmd $tmp_f -t=p -b2=9 -b3=10 -b4=5 -b5=h
-     $reformat_cmd -in $tmp_f-gb -output phylip > $phylip_f
-    else
-     echo "SKIP: $phylip_f exists"
-    fi
+    $gblock_cmd $tmp_f -t=p -b2=9 -b3=10 -b4=5 -b5=h
+    $reformat_cmd -in $tmp_f-gb -output phylip > $phylip_f
     ;;
   "WR")
-    if [ ! -e $phylip_f ]
-    then
-     $tcoffee_cmd -infile $tmp_f -multi_core no -evaluate -output score_ascii -outfile $sa_f -quiet&>/dev/null
-     grep cons $sa_f|tail -n+2|awk '{print $2}'|sed 's/\(.\)\(.\)/\1\n\2/g'|sed 's/\(.\)\(.\)/\1\n\2/g'>tmp.wei
-     $weiSeqboot_cmd $input_phylip tmp.wei
-     mv outfile $phylip_f
-    else
-     echo "SKIP: $phylip_f exists"
-    fi
+    $tcoffee_cmd -infile $tmp_f -multi_core no -evaluate -output score_ascii -outfile $sa_f -quiet&>/dev/null
+    grep cons $sa_f|tail -n+2|awk '{print $2}'|sed 's/\(.\)\(.\)/\1\n\2/g'|sed 's/\(.\)\(.\)/\1\n\2/g'>tmp.wei
+    $weiSeqboot_cmd $input_phylip tmp.wei
+    mv outfile $phylip_f
     ;;
   esac
-  rm -rf tmp.*
+  
+  # Copy result to target data folder
+  [ ! -e $out_p ] && mkdir -p $out_p
+  if [ -e $phylip_f ]; then 
+    mv $phylip_f $out_p
+  else 
+    echo "Missing result: $phylip_f in script genFilter"
+  fi 
+  
+  rm tmp.*
+  
 else
   echo "ERROR: $input_fa not exists"
 fi
+  
